apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: store-app
  namespace: ecom3
  labels:
    team: ecom3
spec:
  selector:
    matchLabels:
      app: store
  endpoints:
    - port: web
      path: /prometheusMetrics
