commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: ecom3

resources:
  - namespace.yml
  # Individual apps
  - invoice-k8s/invoice-deployment.yml
  - invoice-k8s/invoice-service.yml
  - invoice-k8s/invoice-mysql.yml
  - invoice-k8s/invoice-prometheus-sm.yml
  - invoice-k8s/invoice-destination-rule.yml
  - invoice-k8s/invoice-virtual-service.yml
  - notification-k8s/notification-deployment.yml
  - notification-k8s/notification-service.yml
  - notification-k8s/notification-mongodb.yml
  - notification-k8s/notification-prometheus-sm.yml
  - notification-k8s/notification-destination-rule.yml
  - notification-k8s/notification-virtual-service.yml
  - product-k8s/product-deployment.yml
  - product-k8s/product-service.yml
  - product-k8s/product-mysql.yml
  - product-k8s/product-prometheus-sm.yml
  - product-k8s/product-destination-rule.yml
  - product-k8s/product-virtual-service.yml
  - store-k8s/store-deployment.yml
  - store-k8s/store-service.yml
  - store-k8s/store-mysql.yml
  - store-k8s/store-gateway.yml
  - store-k8s/store-prometheus-sm.yml
  - store-k8s/store-destination-rule.yml
  - store-k8s/store-virtual-service.yml
  # monitoring prometheus
  - monitoring-k8s/jhipster-prometheus-cr.yml
  - monitoring-k8s/jhipster-prometheus-crd.yml
  - monitoring-k8s/jhipster-grafana.yml
  - monitoring-k8s/jhipster-grafana-dashboard.yml
  - monitoring-k8s/jhipster-grafana-gateway.yml
  # service discovery eureka/consul
  - registry-k8s/consul.yml
  - registry-k8s/consul-config-loader.yml
  - registry-k8s/application-configmap.yml
  # istio
  - istio-k8s/grafana-gateway.yml
  - istio-k8s/zipkin-gateway.yml
  - istio-k8s/kiali-gateway.yml

patchesJson6902:
  - target:
      version: v1
      kind: Namespace
      name: ecom3
    path: patch-k8s/istio-label.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: grafana-observability-gateway
      namespace: ecom3
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: grafana-gw-virtualservice
      kind: VirtualService
      namespace: ecom3
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: kiali-observability-gateway
      namespace: ecom3
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: kiali-gw-virtualservice
      kind: VirtualService
      namespace: ecom3
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: zipkin-observability-gateway
      namespace: ecom3
    path: patch-k8s/istio-namespace.yml
  - target:
      group: networking.istio.io
      version: v1alpha3
      name: zipkin-gw-virtualservice
      kind: VirtualService
      namespace: ecom3
    path: patch-k8s/istio-namespace.yml
